Improve container image test to wait until the image is downloadable before progressing
Signed-off-by: Pete Wall <pwall@vmware.com>

diff --git a/ci/tasks/test-container-image-product.yaml b/ci/tasks/test-container-image-product.yaml
--- a/ci/tasks/test-container-image-product.yaml
+++ b/ci/tasks/test-container-image-product.yaml
@@ -40,4 +40,16 @@ run:
       fi
 
       # Get the list of images
-      mkpcli product list-assets --type image --product "${PRODUCT_SLUG}" --product-version "${VERSION}" | grep "${TEST_IMAGE_REPO}:${TEST_IMAGE_TAG}"
+      mkpcli product list-assets --product "${PRODUCT_SLUG}" --product-version "${VERSION}"
+
+      # Wait until the image is downloadable
+      asset=$(mkpcli product list-assets --type image --product "${PRODUCT_SLUG}" --product-version "${VERSION}" --output json | jq --arg name "${TEST_IMAGE_REPO}:${TEST_IMAGE_TAG}" '.[] | select(.displayname == $name)')
+      while [ $(echo "${asset}" | jq .downloadable) == "false" ]
+      do
+        if [ $(echo "${asset}" | jq .error) != "null" ]; then
+          exit 1
+        fi
+
+        sleep 30
+        asset=$(mkpcli product list-assets --type image --product "${PRODUCT_SLUG}" --product-version "${VERSION}" --output json | jq --arg name "${TEST_IMAGE_REPO}:${TEST_IMAGE_TAG}" '.[] | select(.displayname == $name)')
+      done
